on:
    push:
      branches: [ main ]

env:
    GH_TOKEN: ${{ github.token }}
        
jobs:
    dag-generator:
        runs-on: ubuntu-latest 

        steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Get branch name (head) of the last merged PR
          id: branch-name
          if: github.event_name != 'pull_request' # do not push DAG on pull request
          run: |
            sudo apt-get update
            sudo apt-get install -y jq
            echo "branch=$(gh pr view ${{ github.event_path.number }} --json headRefName | jq '.[0].headRefName')" | sed 's/"//g' >> "$GITHUB_OUTPUT"
            echo "branch2=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_OUTPUT"
            echo "PR_BRANCH_NAME=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
        
        - name: Display branch name
          run: |
            echo "target-branch: ${{ steps.branch-name.outputs.branch }}"
            echo "target-branch2: ${{ steps.branch-name.outputs.branch2 }}"
            echo "PR_BRANCH_NAME: ${{ steps.branch-name.outputs.PR_BRANCH_NAME }}"
        
        - name: Get PR Branch Name
          id: pr_branch_name
          run: echo "PR_BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
    
        - name: Print PR Branch Name
          run: |
            echo "PR Branch Name is $PR_BRANCH_NAME"
            echo "Commit msg: ${{ github.event.head_commit.message }}"
            echo "base_ref: ${{ github.base_ref }}"
            echo "event_name: ${{ github.event_name }}"
            echo "head_ref: ${{ github.head_ref }}"
            echo "ref: ${{ github.ref }}"
            echo "ref_name: ${{ github.ref_name }}"
            echo "sha: ${{ github.sha }}"
            echo "event number is: ${{ github.event_path.number }}"





              
